### ISSUE TITLE
Feature request: Make service connection creation optional

### ISSUE THREAD

**Issue by abatilo** [GoogleCloudPlatform/terraform-google-cloud-ids#16]
This module creates a service connection but if there's already one defined on the VPC in a different terraform state, then the two terraform states will disagree with each other and the two states will delete/re-create the service connection.

**Comment by legal90** [comment]
@abatilo Even though it's closed, I submitted the PR for that feature here: https://github.com/GoogleCloudPlatform/terraform-google-cloud-ids/pull/40
